name: DAPPER DAN
favicon: null
layout_spectrum: 0.5791134424507618
typography_spectrum: 0.13575908774510026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8572900316212326
  lightness: 0.19836230436339974
  saturation: 0.6702939691022038
  rhythmicContrast: 0.22949562966823578
purpose: []
